//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalData
    {
        public System.DateTime Date { get; set; }
        public string AnimType { get; set; }
        public string AnimName { get; set; }
        public Nullable<int> AnimPrice { get; set; }
        public Nullable<int> AnimQuantity { get; set; }
    }
}
